---
- name: server.yml - basic server setup
  hosts: all

  tasks:
#    - name: Set SELinux in permissive mode, logging actions that would be blocked.
#      selinux:
#        policy: targeted
#        state: permissive
#
    - name: Installation of basic software on servers..
      yum:
        name:
          - git
          - net-tools
          - open-vm-tools
          - vim
        state: present

    - name: Installation of RHEL/CentOS SELinux related software..
      yum:
        name:
          - selinux-policy-targeted
        state: present
      when:
        - ansible_facts['os_family'] == "RedHat"
