---
- name: teslamate.yml - TeslaMate installation in Docker but all automated..
  hosts: teslamate
  vars:
#    ansible_python_interpreter: /usr/bin/python3
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
      - name: compose
      - name: docker
      - name: docker-compose
      - name: requests
      - name: setuptools
      - name: urllib3

  pre_tasks:
    - name: Installation of RHEL/CentOS 7 related software..
      yum:
        name:
          - policycoreutils-python
          - python-virtualenv
          - setuptool
        state: present
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "7"

    - name: Installation of RHEL/CentOS 8 related software..
      yum:
        name:
          - python3-policycoreutils
          - python3-virtualenv
        state: present
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "8"

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: tobiasehlert.teslamate
