---
- name: teslamate.yml - TeslaMate installation automated..
  hosts: teslamate

  vars:
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: present
    docker_install_compose: true
    docker_compose_version: "1.25.4"
    docker_compose_path: /usr/local/bin/docker-compose
    docker_users:
      - tobias
      - ansible
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
      - name: docker
      - name: docker-compose

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: tobiasehlert.teslamate
