---
- name: users.yml - setting up certain users
  hosts: all
  

  tasks:

    - name: Setup Ansible User
      user:
        name: ansible
        comment: Ansible Management User
        generate_ssh_key: yes
        ssh_key_bits: 4096
        state: present

    - name: Add user ansible to sudoers.d folder
      lineinfile:
        path: /etc/sudoers.d/ansible
        line: "ansible ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0440
        create: yes
        validate: "visudo -cf %s"

    - name: Set includedir in sudoers (if not already existing)
      lineinfile:
        dest: /etc/sudoers
        line: "#includedir /etc/sudoers.d"
        state: present
        validate: "/usr/sbin/visudo -cf %s"

    - name: Adding sshkey to list of users
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'files/'+ item +'.pub') }}"
        state: present
      with_items:
        - ansible
        - tobias

